from flask import Flask, render_template, request, jsonify, send_file
import os, subprocess, uuid, threading
from datetime import datetime
from job_store import (load_jobs, save_jobs, save_job, load_batch_jobs,
                        save_batch_jobs, is_recent, job_age_str, categorize_jobs)

app = Flask(__name__)
app.config['UPLOAD_FOLDER'] = 'uploads'
app.config['RESULTS_FOLDER'] = 'results'
app.config['MAX_CONTENT_LENGTH'] = 200 * 1024 * 1024


# ── Auto cleanup ──────────────────────────────────────────────────────────────
import threading as _threading
import time as _time
import shutil as _shutil

def _cleanup_old_files(max_age_hours=48):
    """Hapus folder upload/result/chunk lama (>48 jam)."""
    now = _time.time()
    max_age = max_age_hours * 3600
    for base_dir in [UPLOAD_FOLDER, RESULTS_FOLDER]:
        if not os.path.exists(base_dir): continue
        for name in os.listdir(base_dir):
            path = os.path.join(base_dir, name)
            if not os.path.isdir(path): continue
            if now - os.path.getmtime(path) > max_age:
                try: _shutil.rmtree(path)
                except: pass
    # Cleanup token store
    expired = [k for k, v in _uploaded_files.items()
               if not os.path.exists(v.get('rover', ''))]
    for k in expired: _uploaded_files.pop(k, None)
    expired_c = [k for k, v in _chunk_uploads.items()
                 if not os.path.exists(v.get('chunk_dir', ''))]
    for k in expired_c: _chunk_uploads.pop(k, None)

def _cleanup_loop():
    while True:
        _time.sleep(3600)
        try: _cleanup_old_files()
        except: pass

_threading.Thread(target=_cleanup_loop, daemon=True).start()

# Load persisted jobs dari file (survive restart/refresh)
jobs = load_jobs()

POSITIONING_MODES = {
    'single':'Single Point (Code)', 'dgps':'DGPS/DGNSS',
    'kinematic':'Kinematic', 'static':'Static',
    'ppp-static':'PPP-Static', 'ppp-kinematic':'PPP-Kinematic',
}

MODE_NUM = {'single':'0','dgps':'1','kinematic':'2','static':'3','ppp-kinematic':'5','ppp-static':'6'}
AMB_NUM  = {'off':'0','continuous':'1','instantaneous':'2','fix-and-hold':'3','ppp-ar':'4'}

def build_conf(params, conf_path):
    """Write RTKLIB .conf file from collected params."""
    p = params
    conf = f"""# RTKLIB config generated by GNSS Processor
pos1-posmode       ={MODE_NUM.get(p.get('mode','static'),'3')}  # positioning mode
pos1-frequency     ={p.get('freq','2')}               # frequencies (1:L1 2:L1+L2 3:L1+L2+L5)
pos1-soltype       ={p.get('filter','2')}              # solution type (0:fwd 1:bwd 2:combined)
pos1-elmask        ={p.get('elevation_mask','15')}     # elevation mask (deg)
pos1-snrmask_r     ={p.get('snr_mask','0')}           # SNR mask rover
pos1-snrmask_b     ={p.get('snr_mask','0')}           # SNR mask base
pos1-dynamics      =0                                  # dynamics model (0:off 1:on)
pos1-tidecorr      ={p.get('earth_tides','0')}        # tidal correction (0:off 1:solid 3:solid+otl)
pos1-ionoopt       ={p.get('iono','3')}               # ionosphere opt (0:off 1:brdc 2:sbas 3:dual-freq 4:est 5:ionex)
pos1-tropopt       ={p.get('tropo','1')}              # troposphere opt (0:off 1:saas 2:sbas 3:est)
pos1-sateph        =0                                  # sat ephem (0:brdc 1:prec+brdc)
pos1-posopt1       ={p.get('phase_windup','1')}       # phase windup correction
pos1-posopt2       =1                                  # receiver PCV correction
pos1-posopt3       =0                                  # RAIM FDE
pos1-posopt5       ={p.get('cs_lc','1')}              # cycle slip detection by LC
pos1-exclsats      =                                   # excluded satellites
pos1-navsys        ={p.get('sys_mask','9')}           # nav sys mask (1:GPS 2:SBAS 4:GAL 8:GLO 32:BDS 64:QZS)
pos2-armode        ={AMB_NUM.get(p.get('amb_res','continuous'),'1')}  # AR mode
pos2-gloarmode     =1                                  # GLONASS AR mode
pos2-gaiarmode     =0                                  # Galileo AR mode
pos2-arthres       =3.0                                # AR ratio threshold
pos2-arlockcnt     =0                                  # AR lock count
pos2-arelmask      =0.0                                # AR elevation mask
pos2-arminfix      =10                                 # AR min fix count
pos2-armaxiter     =1                                  # AR max iterations
pos2-elmaskhold    =0.0                                # elevation mask hold
pos2-aroutcnt      =5                                  # AR outage count
pos2-maxage        ={p.get('max_age','30')}           # max age differential (s)
pos2-syncsol       =0                                  # sync solution
pos2-slipthres     =0.05                               # slip threshold
pos2-dopthres      =0.0                                # Doppler threshold
pos2-varholdamb    =0.001                              # hold ambiguity variance
pos2-gainholdamb   =0.01                               # gain to hold ambiguity
pos2-maxgdop       ={p.get('max_gdop','30')}          # max GDOP
pos2-minfixsats    ={p.get('min_sat','4')}            # min fixed satellites
pos2-minholdsats   =5                                  # min hold satellites
pos2-mindropsats   =10                                 # min drop satellites
pos2-rcvstds       =0                                  # receiver stds
pos2-initrst       =1                                  # reset ambiguity on gap
out-solformat      =llh                                # solution format (llh/xyz/enu/nmea)
out-outhead        =1                                  # output header
out-outopt         =1                                  # output processing options
out-outvel         =0                                  # output velocity
out-timesys        =gpst                               # time system
out-timeform       =tow                                # time format
out-timendec       =3                                  # time decimal
out-degform        =deg                                # degree format
out-fieldsep       =                                   # field separator
out-outsingle      =0                                  # output single solutions
out-maxsolstd      =0.0                                # max solution std
out-nmeaintv1      =0.0                                # NMEA interval 1
out-nmeaintv2      =0.0                                # NMEA interval 2
out-rnxopt1        =                                   # RINEX option rover
out-rnxopt2        =                                   # RINEX option base
stats-eratio1      =100                                # code/phase ratio L1
stats-eratio2      =100                                # code/phase ratio L2
stats-errphase     =0.003                              # phase error (m)
stats-errphaseel   =0.003                              # phase error elevation
stats-errphasebl   =0.0                                # phase error baseline
stats-errdoppler   =1.0                                # Doppler error (Hz)
stats-stdbias      =30.0                               # initial bias std
stats-stdiono      =0.03                               # initial iono std
stats-stdtrop      =0.3                                # initial trop std
stats-prnaccelh    =1.0                                # process noise h
stats-prnaccelv    =0.25                               # process noise v
stats-prnbias      =0.0001                             # process noise bias
stats-prniono      =0.001                              # process noise iono
stats-prntrop      =0.0001                             # process noise trop
stats-clkstab      =5e-12                              # clock stability
ant1-postype       ={4 if (p.get('base_lat') and p.get('base_lon')) else 0}   # base position type (0:llh 4:rinexhead)
ant1-pos1          ={p.get('base_lat','0')}           # base latitude (deg)
ant1-pos2          ={p.get('base_lon','0')}           # base longitude (deg)
ant1-pos3          ={p.get('base_ht','0')}            # base height (m)
ant1-anttype       ={p.get('ant_type_base','')}       # base antenna type
ant1-antdele       =0.0                                # base antenna delta E
ant1-antdeln       =0.0                                # base antenna delta N
ant1-antdelu       ={p.get('ant_ht_base','0')}        # base antenna height (m)
ant2-postype       =0                                  # rover position type
ant2-anttype       ={p.get('ant_type_rover','')}      # rover antenna type
ant2-antdele       =0.0                                # rover antenna delta E
ant2-antdeln       =0.0                                # rover antenna delta N
ant2-antdelu       ={p.get('ant_ht_rover','0')}       # rover antenna height (m)
misc-timeinterp    =1                                  # time interpolation base
misc-sbasatsel     =0                                  # SBAS satellite selection
misc-rnxopt1       =                                   # RINEX opt rover
misc-rnxopt2       =                                   # RINEX opt base
"""
    with open(conf_path, 'w') as f:
        f.write(conf)
    return conf_path


def run_processing(job_id, rover, base, nav, sp3, params):
    job = jobs[job_id]
    job['status'] = 'processing'
    result_dir = os.path.join(app.config['RESULTS_FOLDER'], job_id)
    os.makedirs(result_dir, exist_ok=True)
    result_pos  = os.path.join(result_dir, 'result.pos')
    conf_path   = os.path.join(result_dir, 'rtklib.conf')

    # Write config file
    build_conf(params, conf_path)
    job['conf'] = conf_path

    # Download IGS nav jika belum ada
    if not nav or not os.path.exists(str(nav)):
        try:
            from igs_downloader import download_ephemeris
            eph_dir = os.path.join(result_dir, 'eph')
            eph = download_ephemeris(rover, eph_dir, 'broadcast', timeout_total=60)
            if eph.success and eph.nav_file:
                nav = eph.nav_file
                job['nav'] = os.path.basename(nav)
        except Exception as e:
            job['stderr'] = (job.get('stderr') or '') + f' [IGS error: {e}]'

    # Build command
    cmd = ['rnx2rtkp', '-k', conf_path, '-o', result_pos, rover]
    if base and os.path.exists(base): cmd.append(base)
    if nav and os.path.exists(str(nav)): cmd.append(nav)
    if sp3 and os.path.exists(sp3): cmd.append(sp3)

    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=600)
        job['stdout'] = proc.stdout
        job['stderr'] = proc.stderr
        job['returncode'] = proc.returncode
        job['cmd'] = ' '.join(cmd)

        if proc.returncode == 0 and os.path.exists(result_pos):
            job['status'] = 'done'
            job['result_file'] = result_pos
            job['summary'] = parse_pos_file(result_pos)
        elif proc.returncode == 127 or not os.path.exists('/usr/local/bin/rnx2rtkp'):
            job['status'] = 'demo'
            job['summary'] = gen_demo(params.get('mode','static'))
            job['stderr'] = 'rnx2rtkp not installed — demo result. Config file tersimpan di: ' + conf_path
        else:
            job['status'] = 'error'
            job['error'] = proc.stderr or 'Processing failed (rc={})'.format(proc.returncode)
    except FileNotFoundError:
        job['status'] = 'demo'
        job['summary'] = gen_demo(params.get('mode','static'))
        job['stderr'] = 'rnx2rtkp not found. Config: ' + conf_path
    except subprocess.TimeoutExpired:
        job['status'] = 'error'; job['error'] = 'Timeout >600s'
    except Exception as e:
        job['status'] = 'error'; job['error'] = str(e)

    job['finished_at'] = datetime.now().isoformat()
    job['params'] = params
    save_jobs(jobs)  # persist ke disk


def parse_pos_file(filepath):
    rows = []
    try:
        with open(filepath) as f:
            for line in f:
                if line.startswith('%') or not line.strip(): continue
                p = line.split()
                if len(p) >= 8:
                    rows.append({'lat':float(p[2]),'lon':float(p[3]),'height':float(p[4]),'Q':int(p[5])})
    except: pass
    if not rows: return None
    fixed=[r for r in rows if r['Q']==1]
    lats=[r['lat'] for r in rows]; lons=[r['lon'] for r in rows]; hts=[r['height'] for r in rows]
    n=len(rows)
    def mn(v): return sum(v)/len(v)
    def sd(v): m=mn(v); return (sum((x-m)**2 for x in v)/len(v))**.5
    return {
        'total_epochs':n,'fixed_epochs':len(fixed),
        'fix_ratio':round(len(fixed)/n*100,1),
        'lat_mean':round(mn(lats),8),'lon_mean':round(mn(lons),8),'height_mean':round(mn(hts),4),
        'lat_std':round(sd(lats)*111000,5),'lon_std':round(sd(lons)*111000,5),'ht_std':round(sd(hts),5),
    }

def gen_demo(mode):
    import random
    return {
        'total_epochs':3600,'fixed_epochs':3421 if mode=='static' else 1800,
        'fix_ratio':95.0 if mode=='static' else 50.0,
        'lat_mean':round(-7.1665+random.uniform(-0.0001,0.0001),8),
        'lon_mean':round(112.6508+random.uniform(-0.0001,0.0001),8),
        'height_mean':round(12.345+random.uniform(-0.5,0.5),4),
        'lat_std':round(random.uniform(0.002,0.005),5),
        'lon_std':round(random.uniform(0.002,0.005),5),
        'ht_std':round(random.uniform(0.004,0.010),5),
        'demo':True,
    }

@app.route('/')
def index(): return render_template('index.html', modes=POSITIONING_MODES)

@app.route('/process', methods=['POST'])
def process():
    jid = str(uuid.uuid4())[:8]
    ud  = os.path.join(app.config['UPLOAD_FOLDER'], jid)
    os.makedirs(ud, exist_ok=True)

    def save(field):
        f = request.files.get(field)
        if f and f.filename:
            p = os.path.join(ud, f.filename); f.save(p); return p
        return None

    rover=save('rover'); base=save('base'); nav=save('nav'); sp3=save('sp3')
    if not rover or not nav:
        return jsonify({'error':'Rover RINEX dan Navigation file wajib'}), 400

    # Collect ALL params from form
    params = {
        'mode':           request.form.get('mode','static'),
        'elevation_mask': request.form.get('elevation_mask','15'),
        'snr_mask':       request.form.get('snr_mask','0'),
        'amb_res':        request.form.get('amb_res','continuous'),
        'max_gdop':       request.form.get('max_gdop','30'),
        # Base station
        'base_lat':       request.form.get('base_lat',''),
        'base_lon':       request.form.get('base_lon',''),
        'base_ht':        request.form.get('base_ht',''),
        'ant_ht_rover':   request.form.get('ant_ht_rover','0'),
        'ant_ht_rover_type': request.form.get('ant_ht_rover_type','0'),
        'ant_ht_base':    request.form.get('ant_ht_base','0'),
        'ant_ht_base_type': request.form.get('ant_ht_base_type','0'),
        'ant_type_rover': request.form.get('ant_type_rover',''),
        'ant_type_base':  request.form.get('ant_type_base',''),
        # GNSS config
        'freq':           request.form.get('freq','2'),
        'sys_mask':       request.form.get('sys_mask','9'),
        'filter':         request.form.get('filter','2'),
        'min_sat':        request.form.get('min_sat','4'),
        'out_interval':   request.form.get('out_interval','0'),
        # Corrections
        'iono':           request.form.get('iono','3'),
        'tropo':          request.form.get('tropo','1'),
        'earth_tides':    request.form.get('earth_tides','0'),
        'phase_windup':   request.form.get('phase_windup','1'),
        'cs_lc':          request.form.get('cs_lc','1'),
        'cs_gf':          request.form.get('cs_gf','1'),
        'cs_dop':         request.form.get('cs_dop','0'),
        'max_age':        request.form.get('max_age','30'),
    }

    jobs[jid] = {
        'id':jid,'status':'queued','mode':params['mode'],
        'rover':os.path.basename(rover),
        'base':os.path.basename(base) if base else None,
        'nav':os.path.basename(nav),
        'created_at':datetime.now().isoformat(),
        'summary':None,'result_file':None,'error':None,'stdout':'','stderr':'','params':params,
    }

    save_jobs(jobs)  # persist sebelum proses
    threading.Thread(target=run_processing,
                     args=(jid,rover,base,nav,sp3,params),daemon=True).start()
    return jsonify({'job_id':jid})

@app.route('/status/<jid>')
def status(jid):
    j=jobs.get(jid)
    return jsonify(j) if j else (jsonify({'error':'Not found'}),404)

@app.route('/download/<jid>')
def download(jid):
    j=jobs.get(jid)
    if not j or not j.get('result_file'): return 'Not found',404
    return send_file(j['result_file'],as_attachment=True,download_name=f'gnss_{jid}.pos')

@app.route('/config/<jid>')
def download_conf(jid):
    """Download the generated RTKLIB config file."""
    j=jobs.get(jid)
    if not j or not j.get('conf'): return 'Not found',404
    return send_file(j['conf'],as_attachment=True,download_name=f'rtklib_{jid}.conf',
                     mimetype='text/plain')

@app.route('/report/<jid>')
def report(jid):
    j=jobs.get(jid)
    if not j: return 'Job not found',404
    if j['status'] not in ('done','demo'): return 'Job not finished',400
    rd=os.path.join(app.config['RESULTS_FOLDER'],jid)
    os.makedirs(rd,exist_ok=True)
    pdf_path=os.path.join(rd,f'report_{jid}.pdf')
    try:
        from report_generator import generate_report
        generate_report(j, pdf_path)
    except Exception as e:
        import traceback; return f'Report error: {e}\n{traceback.format_exc()}',500
    return send_file(pdf_path,as_attachment=True,
        download_name=f'GNSS_Report_{jid}_{datetime.now().strftime("%Y%m%d")}.pdf',
        mimetype='application/pdf')

@app.route('/jobs')
def list_jobs():
    """Return semua jobs dengan age info."""
    result = []
    for j in jobs.values():
        jc = dict(j)
        jc['age_str']   = job_age_str(j)
        jc['is_recent'] = is_recent(j, hours=24)
        result.append(jc)
    # Sort by created_at descending
    result.sort(key=lambda x: x.get('created_at',''), reverse=True)
    return jsonify(result)

@app.route('/jobs/batch_list')
def jobs_batch_list():
    """Batch list — merged ke /jobs namespace yang berfungsi."""
    from batch_processor import batch_jobs
    result = []
    for b in batch_jobs.values():
        result.append({
            'batch_id':   b.batch_id,
            'status':     b.status,
            'n_points':   len(b.points),
            'n_done':     sum(1 for p in b.points if p.status in ('done','demo')),
            'n_error':    sum(1 for p in b.points if p.status == 'error'),
            'created_at': b.created_at,
            'finished_at':b.finished_at,
            'csv_file':   b.csv_file,
            'pdf_file':   b.pdf_file,
            'shp_file':   b.shp_file,
            'zip_file':   b.zip_file,
        })
    result.sort(key=lambda x: x.get('created_at',''), reverse=True)
    return jsonify(result)

@app.route('/jobs/active')
def list_jobs_active():
    """Return hanya jobs aktif (<=24 jam)."""
    active, _ = categorize_jobs(jobs)
    result = []
    for j in active.values():
        jc = dict(j)
        jc['age_str'] = job_age_str(j)
        result.append(jc)
    result.sort(key=lambda x: x.get('created_at',''), reverse=True)
    return jsonify(result)

@app.route('/jobs/history')
def list_jobs_history():
    """Return jobs history (>24 jam)."""
    _, history = categorize_jobs(jobs)
    result = []
    for j in history.values():
        jc = dict(j)
        jc['age_str'] = job_age_str(j)
        result.append(jc)
    result.sort(key=lambda x: x.get('created_at',''), reverse=True)
    return jsonify(result)

if __name__=='__main__':
    os.makedirs('uploads',exist_ok=True); os.makedirs('results',exist_ok=True)
    app.run(host='0.0.0.0',port=5050,debug=False,threaded=True)


@app.route('/crs/<jid>')
def crs_output(jid):
    """Return all CRS conversions for a job's mean coordinate."""
    j = jobs.get(jid)
    if not j: return jsonify({'error': 'Job not found'}), 404
    if j['status'] not in ('done', 'demo'): return jsonify({'error': 'Job not finished'}), 400
    s = j.get('summary', {})
    lat = s.get('lat_mean', 0)
    lon = s.get('lon_mean', 0)
    h   = s.get('height_mean', 0)
    try:
        from crs_transform import convert_all, results_to_dict
        crs_list = convert_all(lat, lon, h)
        return jsonify({
            'job_id': jid,
            'source': {'lat': lat, 'lon': lon, 'h': h},
            'crs': results_to_dict(crs_list)
        })
    except Exception as e:
        return jsonify({'error': str(e)}), 500


# ══ BATCH PROCESSING ENDPOINTS ════════════════════════════════════════════════

@app.route('/batch/create', methods=['POST'])
def batch_create():
    """Buat batch job baru dari multiple OBS files."""
    import uuid as _uuid
    from batch_processor import BatchJob, BatchPoint, batch_jobs, name_from_file

    bid = _uuid.uuid4().hex[:8]
    upload_dir = os.path.join(app.config['UPLOAD_FOLDER'], f'batch_{bid}')
    result_dir = os.path.join(app.config['RESULTS_FOLDER'], f'batch_{bid}')
    os.makedirs(upload_dir, exist_ok=True)

    # Upload OBS files
    obs_files = request.files.getlist('obs_files')
    if not obs_files or not obs_files[0].filename:
        return jsonify({'error': 'Minimal 1 file OBS diperlukan'}), 400

    # Parse per-file antenna heights
    import json as _json
    try:
        ant_heights_arr = _json.loads(request.form.get('ant_heights', '[]'))
    except Exception:
        ant_heights_arr = []

    points = []
    for i, f in enumerate(obs_files):
        if not f.filename: continue
        path = os.path.join(upload_dir, f.filename)
        f.save(path)
        ant_h = ant_heights_arr[i] if i < len(ant_heights_arr) else '0'
        pt = BatchPoint(
            idx=i, name=name_from_file(path), obs_file=path,
            ant_height=str(ant_h) if ant_h else '0'
        )
        points.append(pt)

    # Base file (opsional)
    base_file = None
    bf = request.files.get('base_file')
    if bf and bf.filename:
        bp = os.path.join(upload_dir, bf.filename)
        bf.save(bp)
        base_file = bp

    # Params
    params = {
        'mode':           request.form.get('mode','static'),
        'elevation_mask': request.form.get('elevation_mask','15'),
        'snr_mask':       request.form.get('snr_mask','0'),
        'amb_res':        request.form.get('amb_res','continuous'),
        'max_gdop':       request.form.get('max_gdop','30'),
        'freq':           request.form.get('freq','2'),
        'sys_mask':       request.form.get('sys_mask','9'),
        'filter':         request.form.get('filter','2'),
        'iono':           request.form.get('iono','3'),
        'tropo':          request.form.get('tropo','1'),
        'ant_ht_rover':   request.form.get('ant_ht_rover','0'),
        'ant_ht_rover_type': request.form.get('ant_ht_rover_type','0'),
        'base_lat':       request.form.get('base_lat',''),
        'base_lon':       request.form.get('base_lon',''),
        'base_ht':        request.form.get('base_ht',''),
        'ant_ht_base':    request.form.get('ant_ht_base','0'),
        'phase_windup':   request.form.get('phase_windup','1'),
        'earth_tides':    request.form.get('earth_tides','0'),
        'cs_lc':          request.form.get('cs_lc','1'),
        'cs_gf':          request.form.get('cs_gf','1'),
        'cs_dop':         request.form.get('cs_dop','0'),
        'max_age':        request.form.get('max_age','30'),
        'min_sat':        request.form.get('min_sat','4'),
        'out_interval':   request.form.get('out_interval','0'),
    }

    eph_type = request.form.get('ephemeris_type', 'broadcast')

    batch = BatchJob(
        batch_id    = bid,
        status      = 'queued',
        points      = points,
        params      = params,
        ephemeris_type = eph_type,
        base_file   = base_file,
        result_dir  = result_dir,
        created_at  = datetime.now().isoformat(),
    )
    batch_jobs[bid] = batch

    # Run in background thread
    import threading
    t = threading.Thread(
        target=_run_batch_thread,
        args=(bid,),
        daemon=True
    )
    t.start()

    return jsonify({'batch_id': bid, 'n_points': len(points)})


def _run_batch_thread(bid: str):
    from batch_processor import run_batch, batch_jobs
    run_batch(bid, jobs)


@app.route('/batch/status/<bid>')
def batch_status(bid):
    from batch_processor import batch_jobs
    b = batch_jobs.get(bid)
    if not b: return jsonify({'error': 'Batch not found'}), 404
    return jsonify({
        'batch_id':   b.batch_id,
        'status':     b.status,
        'n_total':    len(b.points),
        'n_done':     sum(1 for p in b.points if p.status in ('done','demo')),
        'n_error':    sum(1 for p in b.points if p.status == 'error'),
        'n_running':  sum(1 for p in b.points if p.status in ('processing','downloading')),
        'points': [{
            'idx':      p.idx,
            'name':     p.name,
            'status':   p.status,
            'progress': p.progress,
            'error':    p.error,
            'summary':  p.summary,
            'eph_messages': p.eph_messages[-5:],
        } for p in b.points],
        'csv_ready':  bool(b.csv_file and os.path.exists(b.csv_file)),
        'shp_ready':  bool(b.shp_file and os.path.exists(b.shp_file)),
        'pdf_ready':  bool(b.pdf_file and os.path.exists(b.pdf_file)),
        'zip_ready':  bool(b.zip_file and os.path.exists(b.zip_file)),
    })


@app.route('/batch/download/<bid>/<filetype>')
def batch_download(bid, filetype):
    from batch_processor import batch_jobs
    b = batch_jobs.get(bid)
    if not b: return 'Not found', 404
    file_map = {
        'csv': (b.csv_file, f'batch_{bid}.csv',      'text/csv'),
        'pdf': (b.pdf_file, f'batch_{bid}_report.pdf','application/pdf'),
        'zip': (b.zip_file, f'batch_{bid}_output.zip','application/zip'),
        'shp': (b.shp_file, f'batch_{bid}_points.shp','application/octet-stream'),
    }
    if filetype not in file_map: return 'Invalid type', 400
    fpath, fname, mime = file_map[filetype]
    if not fpath or not os.path.exists(fpath): return 'File not ready', 404
    return send_file(fpath, as_attachment=True, download_name=fname, mimetype=mime)


@app.route('/batch/list')
def batch_list():
    from batch_processor import batch_jobs
    return jsonify([{
        'batch_id':  b.batch_id,
        'status':    b.status,
        'n_points':  len(b.points),
        'n_done':    sum(1 for p in b.points if p.status in ('done','demo')),
        'created_at':b.created_at,
    } for b in batch_jobs.values()])


# ── IGS ephemeris auto-download endpoint ──────────────────────────────────────

@app.route('/igs/check', methods=['POST'])
def igs_check():
    """Cek tanggal dari OBS file dan ketersediaan ephemeris di IGS."""
    f = request.files.get('obs_file')
    if not f: return jsonify({'error': 'No file'}), 400
    tmp = os.path.join(app.config['UPLOAD_FOLDER'], f.filename)
    f.save(tmp)
    try:
        from igs_downloader import parse_rinex_date, doy_from_date, gps_week_dow
        from datetime import datetime as dt2
        date = parse_rinex_date(tmp)
        if not date:
            return jsonify({'error': 'Tidak bisa membaca tanggal dari file OBS'})
        y, m, d = date
        doy = doy_from_date(y, m, d)
        week, dow = gps_week_dow(y, m, d)
        age = (dt2.now() - dt2(y,m,d)).days
        return jsonify({
            'date':       f'{y}-{m:02d}-{d:02d}',
            'doy':        doy,
            'gps_week':   week,
            'gps_dow':    dow,
            'age_days':   age,
            'broadcast_available': True,
            'rapid_available':     age >= 2,
            'final_available':     age >= 14,
        })
    finally:
        if os.path.exists(tmp): os.remove(tmp)


# ── RINEX header parser endpoint (server fallback) ────────────────────────────
@app.route('/parse_header', methods=['POST'])
def parse_header():
    """Parse RINEX OBS header — server fallback untuk file binary/compressed."""
    f = request.files.get('obs_file')
    if not f:
        return jsonify({'error': 'No file'}), 400

    tmp = os.path.join(app.config['UPLOAD_FOLDER'], f'tmp_{f.filename}')
    f.save(tmp)

    result = {
        'antHeight':  '',
        'antType':    '',
        'markerName': '',
        'approxPos':  None,
        'recType':    '',
        'interval':   '',
    }

    try:
        # Try plain text first
        try:
            with open(tmp, 'r', errors='ignore') as fh:
                lines = fh.readlines()
        except Exception:
            lines = []

        # If file is compressed (.Z or .gz), try decompress
        if not lines or (lines and len(lines[0]) < 5):
            import gzip
            try:
                with gzip.open(tmp, 'rt', errors='ignore') as fh:
                    lines = fh.readlines()
            except Exception:
                pass

        for line in lines[:200]:  # header max ~200 baris
            if 'END OF HEADER' in line:
                break
            if 'ANTENNA: DELTA H/E/N' in line:
                try:
                    h = float(line[:14].strip())
                    if h >= 0:
                        result['antHeight'] = f'{h:.3f}'
                except ValueError:
                    pass
            if 'ANT # / TYPE' in line:
                t = line[20:40].strip()
                if t:
                    result['antType'] = t
            if 'MARKER NAME' in line:
                m = line[:60].strip()
                if m:
                    result['markerName'] = m
            if 'REC # / TYPE / VERS' in line:
                r = line[20:40].strip()
                if r:
                    result['recType'] = r
            if 'INTERVAL' in line:
                try:
                    iv = float(line[:10].strip())
                    result['interval'] = f'{iv:.3f}'
                except ValueError:
                    pass
            if 'APPROX POSITION XYZ' in line:
                try:
                    x = float(line[0:14].strip())
                    y = float(line[14:28].strip())
                    z = float(line[28:42].strip())
                    result['approxPos'] = {'x': x, 'y': y, 'z': z}
                except ValueError:
                    pass

    except Exception as e:
        result['error'] = str(e)
    finally:
        if os.path.exists(tmp):
            os.remove(tmp)

    return jsonify(result)


@app.route('/check_internet')
def check_internet():
    """Quick check apakah container bisa akses internet."""
    import urllib.request
    try:
        urllib.request.urlopen('http://clients3.google.com/generate_204',
                               timeout=3)
        return jsonify({'ok': True})
    except Exception:
        return jsonify({'ok': False})


# ── Pre-upload endpoint ───────────────────────────────────────────────────────
import tempfile as _tempfile

# Store uploaded file paths per session token
_uploaded_files = {}

# Store chunk assembly state: {upload_id: {path, total_chunks, received, filename}}
_chunk_uploads = {}

@app.route('/upload/chunk', methods=['POST'])
def upload_chunk():
    """Terima satu chunk dari file besar. Dipanggil berulang dari JS.
    State disimpan di filesystem agar aman dengan multi-worker gunicorn."""
    upload_id    = request.form.get('upload_id', '')
    chunk_index  = int(request.form.get('chunk_index', 0))
    total_chunks = int(request.form.get('total_chunks', 1))
    filename     = request.form.get('filename', 'file.obs')
    file_type    = request.form.get('file_type', 'rover')
    token        = request.form.get('token', '')

    chunk = request.files.get('chunk')
    if not chunk:
        return jsonify({'error': 'No chunk data'}), 400

    # Buat direktori temp untuk upload_id ini
    chunk_dir = os.path.join(app.config['UPLOAD_FOLDER'], f'chunks_{upload_id}')
    os.makedirs(chunk_dir, exist_ok=True)

    # Simpan metadata ke file (bukan memory — aman untuk multi-worker)
    meta_path = os.path.join(chunk_dir, '_meta.json')
    if not os.path.exists(meta_path):
        import json as _json
        with open(meta_path, 'w') as mf:
            _json.dump({
                'filename':     filename,
                'total_chunks': total_chunks,
                'file_type':    file_type,
                'token':        token,
            }, mf)

    # Simpan chunk ke file
    chunk_path = os.path.join(chunk_dir, f'chunk_{chunk_index:05d}')
    chunk.save(chunk_path)

    # Hitung received dari filesystem (bukan memory)
    received = len([f for f in os.listdir(chunk_dir)
                    if f.startswith('chunk_') and not f.endswith('.tmp')])

    # Belum semua chunk diterima
    if received < total_chunks:
        return jsonify({'received': received, 'total': total_chunks, 'done': False})

    # Semua chunk diterima — gabungkan
    state = _chunk_uploads[upload_id]
    if file_type == 'rover':
        dest_token = str(__import__('uuid').uuid4())[:8]
        dest_dir   = os.path.join(app.config['UPLOAD_FOLDER'], f'pre_{dest_token}')
    else:
        dest_token = token
        if token and token in _uploaded_files:
            dest_dir = os.path.dirname(_uploaded_files[token]['rover'])
        else:
            dest_dir = os.path.join(app.config['UPLOAD_FOLDER'], f'base_{token}')
    os.makedirs(dest_dir, exist_ok=True)

    final_path = os.path.join(dest_dir, filename)
    with open(final_path, 'wb') as out:
        for i in range(total_chunks):
            cp = os.path.join(chunk_dir, f'chunk_{i:05d}')
            with open(cp, 'rb') as cf:
                out.write(cf.read())

    # Bersihkan chunks
    import shutil
    shutil.rmtree(chunk_dir, ignore_errors=True)
    del _chunk_uploads[upload_id]

    result = {'done': True, 'filename': filename, 'size': os.path.getsize(final_path)}

    if file_type == 'rover':
        _uploaded_files[dest_token] = {
            'rover': final_path, 'name': filename,
            'size':  os.path.getsize(final_path)
        }
        # Parse RINEX header untuk ant height
        ant_height = ''
        try:
            with open(final_path, 'r', errors='ignore') as fh:
                for line in fh.readlines()[:100]:
                    if 'END OF HEADER' in line: break
                    if 'ANTENNA: DELTA H/E/N' in line:
                        h = float(line[:14].strip())
                        if h >= 0: ant_height = f'{h:.3f}'
        except: pass
        result['token']      = dest_token
        result['ant_height'] = ant_height

    else:
        # Parse base header
        ant_height = ''; lat = ''; lon = ''; h_str = ''
        try:
            with open(final_path, 'r', errors='ignore') as fh:
                for line in fh.readlines()[:100]:
                    if 'END OF HEADER' in line: break
                    if 'ANTENNA: DELTA H/E/N' in line:
                        hv = float(line[:14].strip())
                        if hv >= 0: ant_height = f'{hv:.3f}'
                    if 'APPROX POSITION XYZ' in line:
                        import math
                        x=float(line[:14].strip()); y=float(line[14:28].strip()); z=float(line[28:42].strip())
                        a=6378137.0; e2=0.00669437999014
                        lon_r=math.atan2(y,x)
                        lat_r=math.atan2(z,math.sqrt(x*x+y*y))
                        for _ in range(10):
                            N=a/math.sqrt(1-e2*math.sin(lat_r)**2)
                            lat2=math.atan2(z+e2*N*math.sin(lat_r),math.sqrt(x*x+y*y))
                            if abs(lat2-lat_r)<1e-12: lat_r=lat2; break
                            lat_r=lat2
                        N=a/math.sqrt(1-e2*math.sin(lat_r)**2)
                        ht=math.sqrt(x*x+y*y)/math.cos(lat_r)-N
                        lat=f'{math.degrees(lat_r):.8f}'
                        lon=f'{math.degrees(lon_r):.8f}'
                        h_str=f'{ht:.4f}'
        except: pass
        if token in _uploaded_files:
            _uploaded_files[token]['base'] = final_path
        result.update({'ant_height': ant_height, 'lat': lat, 'lon': lon,
                        'h': h_str, 'path': final_path})

    return jsonify(result)

@app.route('/upload/rover', methods=['POST'])
def upload_rover():
    """Upload rover OBS file, return token."""
    f = request.files.get('file')
    if not f: return jsonify({'error': 'No file'}), 400
    token = str(__import__('uuid').uuid4())[:8]
    upload_dir = os.path.join(app.config['UPLOAD_FOLDER'], f'pre_{token}')
    os.makedirs(upload_dir, exist_ok=True)
    path = os.path.join(upload_dir, f.filename)
    f.save(path)
    _uploaded_files[token] = {'rover': path, 'name': f.filename,
                               'size': os.path.getsize(path)}
    # Parse RINEX header for ant height
    from igs_downloader import parse_rinex_date
    ant_height = ''
    try:
        with open(path, 'r', errors='ignore') as fh:
            for line in fh.readlines()[:100]:
                if 'END OF HEADER' in line: break
                if 'ANTENNA: DELTA H/E/N' in line:
                    h = float(line[:14].strip())
                    if h >= 0: ant_height = f'{h:.3f}'
    except: pass
    return jsonify({'token': token, 'filename': f.filename,
                    'size': os.path.getsize(path), 'ant_height': ant_height})

@app.route('/upload/base', methods=['POST'])
def upload_base():
    """Upload base OBS file, attach to token."""
    f = request.files.get('file')
    token = request.form.get('token', '')
    if not f: return jsonify({'error': 'No file'}), 400
    if token and token in _uploaded_files:
        upload_dir = os.path.dirname(_uploaded_files[token]['rover'])
    else:
        upload_dir = os.path.join(app.config['UPLOAD_FOLDER'], f'base_{token}')
        os.makedirs(upload_dir, exist_ok=True)
    path = os.path.join(upload_dir, f.filename)
    f.save(path)
    # Parse base header
    result = {'filename': f.filename, 'size': os.path.getsize(path),
              'ant_height': '', 'lat': '', 'lon': '', 'h': ''}
    try:
        with open(path, 'r', errors='ignore') as fh:
            for line in fh.readlines()[:100]:
                if 'END OF HEADER' in line: break
                if 'ANTENNA: DELTA H/E/N' in line:
                    h = float(line[:14].strip())
                    if h >= 0: result['ant_height'] = f'{h:.3f}'
                if 'APPROX POSITION XYZ' in line:
                    x=float(line[:14].strip()); y=float(line[14:28].strip()); z=float(line[28:42].strip())
                    import math
                    a=6378137.0; e2=0.00669437999014
                    lon=math.atan2(y,x)
                    lat=math.atan2(z,math.sqrt(x*x+y*y))
                    for _ in range(10):
                        N=a/math.sqrt(1-e2*math.sin(lat)**2)
                        lat2=math.atan2(z+e2*N*math.sin(lat),math.sqrt(x*x+y*y))
                        if abs(lat2-lat)<1e-12: lat=lat2; break
                        lat=lat2
                    N=a/math.sqrt(1-e2*math.sin(lat)**2)
                    ht=math.sqrt(x*x+y*y)/math.cos(lat)-N
                    result['lat']=f'{math.degrees(lat):.8f}'
                    result['lon']=f'{math.degrees(lon):.8f}'
                    result['h']=f'{ht:.4f}'
    except: pass
    if token in _uploaded_files:
        _uploaded_files[token]['base'] = path
    result['path'] = path
    return jsonify(result)

@app.route('/upload/process', methods=['POST'])
def upload_process():
    """Start processing using pre-uploaded files."""
    import uuid as _uuid
    data = request.get_json()
    tokens = data.get('tokens', [])
    params = data.get('params', {})
    base_path = data.get('base_path', '')
    eph_source = data.get('ephemeris_source', 'igs')
    eph_type   = data.get('ephemeris_type', 'broadcast')

    if not tokens:
        return jsonify({'error': 'Tidak ada file yang diupload'}), 400

    if len(tokens) == 1:
        # Single processing
        token = tokens[0]
        info  = _uploaded_files.get(token, {})
        rover = info.get('rover', '')
        if not rover or not os.path.exists(rover):
            return jsonify({'error': 'File rover tidak ditemukan'}), 400

        jid = _uuid.uuid4().hex[:8]
        ant_heights = data.get('ant_heights', ['0'])
        params['ant_ht_rover'] = ant_heights[0] if ant_heights else '0'

        # Nav file
        nav = None
        if eph_source == 'manual':
            nav = info.get('nav', '')
        base = base_path or info.get('base', '')

        result_dir = os.path.join(app.config['RESULTS_FOLDER'], jid)
        os.makedirs(result_dir, exist_ok=True)

        jobs[jid] = {
            'id': jid, 'status': 'queued', 'mode': params.get('mode','static'),
            'rover': os.path.basename(rover),
            'base':  os.path.basename(base) if base else None,
            'nav':   os.path.basename(nav) if nav else 'IGS Auto',
            'created_at': datetime.now().isoformat(),
            'summary': None, 'result_file': None, 'error': None,
            'stdout': '', 'stderr': '', 'params': params,
        }
        save_jobs(jobs)

        import threading
        threading.Thread(
            target=run_processing,
            args=(jid, rover, base or None, nav or '', None, params),
            daemon=True
        ).start()
        return jsonify({'job_id': jid, 'type': 'single'})

    else:
        # Batch processing
        from batch_processor import BatchJob, BatchPoint, batch_jobs, name_from_file
        bid = _uuid.uuid4().hex[:8]
        result_dir = os.path.join(app.config['RESULTS_FOLDER'], f'batch_{bid}')
        os.makedirs(result_dir, exist_ok=True)

        ant_heights = data.get('ant_heights', [])
        points = []
        for i, token in enumerate(tokens):
            info  = _uploaded_files.get(token, {})
            rover = info.get('rover', '')
            if not rover: continue
            ant_h = ant_heights[i] if i < len(ant_heights) else '0'
            pt = BatchPoint(idx=i, name=name_from_file(rover),
                            obs_file=rover, ant_height=str(ant_h) if ant_h else '0')
            points.append(pt)

        batch = BatchJob(
            batch_id=bid, status='queued', points=points,
            params=params, ephemeris_type=eph_type,
            base_file=base_path or None, result_dir=result_dir,
            created_at=datetime.now().isoformat(),
        )
        batch_jobs[bid] = batch

        import threading
        threading.Thread(target=_run_batch_thread, args=(bid,), daemon=True).start()
        return jsonify({'batch_id': bid, 'n_points': len(points), 'type': 'batch'})
